### ISSUE TITLE
Optional plugin

### ISSUE THREAD

**Issue by JoryHogeveen** [Automattic/developer#77]
Hi!

Since this plugin promotes other plugins.. I would like to humbly submit my plugin.

https://wordpress.org/plugins/view-admin-as/

It has some crossover functionalities with User Switching since this one also handles switching users.

Info: (copied from wordpress.org):

**Overview / Features**

- Switch to the view of a user to see their capabilities and settings (admins are filtered!)
- Edit this user's screen preferences and settings
- Switch to a default view of a role
- Temporarily change your own capabilities (non-destructively)
- Do this all without loggin out and easily go back to your own (default) user view!

**Module: Role defaults**

- Set default screens for roles
- Apply defaults to a user
- Apply defaults to all users of a role
- Apply defaults when registering a new user (in a multisite this is done when a user is added to its first blog)

**Features planned for future releases:**

- Import/Export role defaults
- Network-wide role defaults (as optional)
- (Since this plugin requires the admin bar): Other options for view management beside the admin bar
- I've had a request for permanent capability management though I'm not sure yet if I want this plugin to handle permanent changes.
- **Input and ideas for features are welcome**

It would be awesome if this plugin could be featured. Take a look and let me know!

Regards, Jory

**Comment by joshbetz** [comment]
Howdy, It looks like we already have most of this functionality with User Switching. Thanks though!

**Comment by JoryHogeveen** [comment]
I'd have to disagree but ok!

**Comment by JoryHogeveen** [comment]
Features update since this issue.

- Switch between user accounts
  - Edit this user’s screen preferences and settings
- Switch between roles
- Temporarily change your own capabilities (non-destructively)
- View your site as an unregistered visitor
- Easily switch back anytime/anywhere
- Do this all without logging out and easily go back to your own (default) user view!

**MODULE: ROLE DEFAULTS (SCREEN SETTINGS)**

- Set default screen settings for roles
- Apply defaults to a user
- Apply defaults to all users of a role
- Apply defaults when registering a new user (in a multisite this is done when a user is added to its first blog)
- Copy defaults from one role to another (or multiple)
- Import/Export role defaults > _Next release: import/export with setting files_
- Disable the “screen settings” option and/or lock the meta boxes for all users that don’t have access to this plugin

**MODULE: ROLE MANAGER (ROLE EDITOR)**
_Note: Changes made with the Role Manager are permanent!_

- Add, edit or delete roles
- Grant and/or add capabilities to roles
- Rename roles
- Clone roles
- Import/Export roles > _Next release: import/export with setting files_
- Update role capabilities from current view
